name: OSSF Scorecard

on:
  push:
    branches: [ main, stage ]
  pull_request:
    branches: [ main ]

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest

    steps:
      - name: Check out main branch code
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: false

      - name: Run OSSF Scorecard analysis
        uses: ossf/scorecard-action@v2.3.1
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          publish_results: true
